### ISSUE TITLE
@types/sass.js npm package

### ISSUE THREAD

**Issue by TheRakeshPurohit** [medialize/sass.js#137]

**Comment by crutchcorn** [comment]
I'm working on TypeScript definition files for this project right now

**Comment by fastcode-inc** [comment]
@crutchcorn any update?

**Comment by TheRakeshPurohit** [comment]
> I'm working on TypeScript definition files for this project right now

any progress ?

**Comment by crutchcorn** [comment]
https://github.com/crutchcorn/sass.js/tree/master/types

This has been the most progress I've gotten thus far. I had to switch contexts fairly quickly after making the comment and priorities have shifted. However, this should be a good start for anyone else looking to pick up the work

Heads up: This is a tricky library to type due to its build methodology
