### ISSUE TITLE
medialize.github.io/sass.js does not work

### ISSUE THREAD

**Issue by andreasmischke** [medialize/sass.js#21]
Wenn launching http://medialize.github.io/sass.js/ I get an error in dev console:
Uncaught 5300312 in /sass.js/dist/worker.min.js:5544
And the [Convert] Button does not work.

I'm running Chrome Version 41.0.2267.0 dev-m (64-bit)

**Comment by rodneyrehm** [comment]
I'm able to reproduce the problem and have opened an [issue with emscripten](https://github.com/kripken/emscripten/issues/3126). I have no idea what went wrong here and suggest you roll back to [v0.6.0](https://github.com/medialize/sass.js/releases/tag/v0.6.0) using libsass 3.0.2 for now.

**Comment by rodneyrehm** [comment]
I was running an outdated version of emscripten. After updating it, compilation fails completely. [emscripten #3137](https://github.com/kripken/emscripten/issues/3137) may help figure out what's going on.

**Comment by rodneyrehm** [comment]
oh man… kinda embarrassing. I was using a very old version of emscripten because I had punched absolute paths into my ENV. After being forced to switch to a new machine, having to install everything anew, compilation worked again.

see [v0.6.2](https://github.com/medialize/sass.js/releases/tag/v0.6.2)
