### ISSUE TITLE
Create distributable that I can include on my page that will automatically compile all type="text/scss" assets to <style> tags

### ISSUE THREAD

**Issue by secrettriangle** [medialize/sass.js#28]

**Comment by rodneyrehm** [comment]
While Sass.js certainly *allows* this to be done. I did not want to foster it by including in sass.js.

**Comment by asciidisco** [comment]
@secrettriangle You could simply write a wrapper that does depend on `sass.js`that does this.
I agree qith @rodneyrehm; this does not belong in "core".

**Comment by varemenos** [comment]
I agree, this isn't a functionality that belongs to the core. We could make a new repository that provides this wrapper though.

**Comment by secrettriangle** [comment]
LESS.js already does this, why shouldn't Sass.js?

@rodneyrehm my use case is that I want to just drop the file into my `index.html` during development. I would eventually remove the include and write a sass compilation script when I go to deploy. I don't think that's so unreasonable.

@varemenos @asciidisco I understand your concern. However in my opinion there is a point at which modularity interferes with usability. I think the majority of people who visit this page come looking for such functionality and are dismayed when they can't find it, but I suspect they simply do not care enough to create a bug report.

**Comment by rodneyrehm** [comment]
> LESS.js already does this, why shouldn't Sass.js?

because it's comparably slow to this stuff in the client.

> my use case is that I want to just drop the file into my index.html during development.

What do you hope to gain from this, other than not having a "watcher" running that recompiles the output file upon change? This makes sense if - and only if - you want to edit your SCSS without having a sass processor installed on the system you're working on.

> I don't think that's so unreasonable.

not unreasonable at all. I don't think it'll be anywhere as fast as you'd like it to be, but that doesn't make it unreasonable.

> but I suspect they simply do not care enough

Ok, so they wan't something but don't want it enough to ask for it?

---

Sass.js is focused on making libsass available in the browser. As libsass is a library, Sass.js is a library. neither does anything fancy on their own. They are a tool to be used by or integrated into another tool.

What you're asking for is not unreasonable, it's just not the scope of this library. All tools required to actually build this feature are available today. I encourage you to try building this yourself, in a separate project. You are welcome to ask for help/advice any time. I'd like to see this feature built - even though it won't be part of Sass.js. (maybe we can make it live.sass.js, like we have playground.sass.js)?

**Comment by secrettriangle** [comment]
Sorry, but I still fail to see why Sass.js can't do what all the other frontend CSS preprocessor libraries do. You're not making something "beautiful", you're making something that *does the job*. (I hope.) A small file that simply finds all `type="text/scss"` files and automatically compiles them is so miniscule, yet so useful, that even RMS might reconsider his philosophy for the sake of practicality.

**Comment by bassjobsen** [comment]
possible try / see: https://github.com/mgreter/sass.link.js

**Comment by rodneyrehm** [comment]
The scope of Sass.js is to provide a convenient interface to libsass. It does not, should not and will not contain *any* integrations for *any* system. like libsass, its only task is to take a SCSS string an compile it to CSS. It does not care how you obtain the SCSS. It does not care how you use the CSS. It does not even care *where* it's being run - browser, node, or even the [JVM](https://twitter.com/mrdrjennings/status/586581653688037377).

That said, everyone agrees with the suggested feature. It has, in fact been tried before, as pointed out by @bassjobsen. We're not saying that we will not not implment this feature. We're saying we won't implement it in Sass.js. We can talk about creating a second project (e.g. *link.sass.js* or *browser.sass.js* or *web.sass.js*, …) that deals with the problems of finding and downloading sass files from `<link>` elements and provides an importer callback, to resolve nested `@import` statements (capable of resolving [relative URLs](http://medialize.github.io/URI.js/docs.html#absoluteto)).

You are free to implement the feature yourself, in a separate project, making *you* the person filling the biggest gap between Sass and LESS in the browser. Or you can wait for someone else to figure it out. It may be one of the sass.js guys - it may not. It depends on our own needs. Nobody is in the business of writing software they don't need themselves (unless they're being paid for it). That's not how voluntary open source works.

Again I shall note that, should you (or anyone, really) decide to try implementing this feature, we're here to help.

**Comment by rodneyrehm** [comment]
I've created [bower-sass](https://github.com/medialize/browser-sass) (and registered it with npm and bower) to host the features relevant to making that `<link>` thing work. The Sass.js team has access to that repository. I suggest we move the discussion over there…
