### ISSUE TITLE
Calling javascript functions

### ISSUE THREAD

**Issue by GarouDan** [medialize/sass.js#38]
I trying to use sass.js and sass.link.js (to compile scss on the fly), to Apache Cordova projects. How can I call javascript methods with sass.js?

For example, in less I will wrote:

@maxPxWidth: `Math.max(document.documentElement.clientWidth, window.innerWidth || 0)`;
@maxPxHeight: `Math.max(document.documentElement.clientHeight, window.innerHeight || 0)`;

How could we do this with sass.js?

**Comment by rodneyrehm** [comment]
Executing JS from Sass is *not possible* in Sass.js. Sass.js is *not* inteded to run on your clients, unless a key component of your client is generating CSS from Sass. That said, you can always calculate your things, generate valid SCSS containing your variables and save that to the Sass.js file system to be `@import`ed by other files.

**Comment by GarouDan** [comment]
I see. Well, sass.link.js can compile scss files on the fly to me. But, if we are using nodejs, for example, not on client, can't we or couldn't  would be a good thing run some javascript code to help us?

**Comment by rodneyrehm** [comment]
> I see. Well, sass.link.js can compile scss files on the fly to me.

Are you referring to [sass.link.js](https://github.com/mgreter/sass.link.js)? Please have a look at the commit history to see that nothing has been done over there for a year. Please also look at how resolving files over the network is a problem.

sass.js knows lazyFiles() and preloadFiles() as explained in the Readme: [Working With Files](https://github.com/medialize/sass.js#working-with-files). If you need to go deeper than that, a [custom importer function](https://github.com/medialize/sass.js#importer-callback-function) may help.

> But, if we are using nodejs, for example, not on client […]

then you'd be using the much faster [node-sass](https://github.com/sass/node-sass) instead of sass.js

> […] can't we or couldn't would be a good thing run some javascript code to help us?

You could make use of [sass functions](https://github.com/sass/node-sass#functions--v300---experimental), which allows you to register JavaScript callbacks for sass functions. This is using an extension API in libsass that I haven't gotten around to implement in sass.js yet (tracked in issue #27).

**Comment by rodneyrehm** [comment]
closing for lack of feedback/activity
