### ISSUE TITLE
Compiler error: argument `$color` of `lightness($color)` must be a color

### ISSUE THREAD

**Issue by emyarod** [medialize/sass.js#53]
After preloading bourbon.io and my sass source files, the sass.js compiler keeps throwing this error:

```
argument `$color` of `lightness($color)` must be a color
Backtrace:
	sass/flattish/utils/_functions.scss:6, in function `lightness`
	sass/flattish/utils/_functions.scss:6, in function `set-text-color`
	sass/flattish/components/_buttons.scss:214
```

However, my stylesheet compiles with no errors in node-sass as well as in [this atom package](https://atom.io/packages/sass-autocompile). I'm attempting to load and compile my [entire project](https://github.com/emyarod/flattish/tree/master/style) in sass.js

**Comment by rodneyrehm** [comment]
which versions of sass.js and node-sass are you using here? I've just published [0.9.9](https://github.com/medialize/sass.js/releases/tag/0.9.9) (upgrading to libsass 3.3.5) - does your problem still exist?

**Comment by emyarod** [comment]
I'm using node-sass version 3.4.2, and I've just updated my sass.js/dist to 0.9.9. Unfortunately I'm still getting the same error. I'm starting to think that perhaps I'm not loading sass.js correctly in my project?

**Comment by rodneyrehm** [comment]
> I'm using node-sass version 3.4.2, and I've just updated my sass.js/dist to 0.9.9. Unfortunately I'm still getting the same error.

[node-sass 3.4.2](https://github.com/sass/node-sass/releases/tag/v3.4.2) is using [libsass 3.3.2](https://github.com/sass/libsass/releases/tag/3.3.2), sass.js 0.9.9 is using [libsass 3.3.5](https://github.com/sass/libsass/releases/tag/3.3.5). You could try [sassc](http://sass-lang.com/libsass) or one of the other wrappers using a newer version of libsass to verify the issue.

Or go the other way around and try sass.js [0.9.4](https://github.com/medialize/sass.js/releases/tag/0.9.4) (using libsass 3.3.1) or [0.9.5](https://github.com/medialize/sass.js/releases/tag/0.9.5) (using libsass 3.3.3) to verify the problem did not exist in that version. (I don't have a libsass 3.3.2 build, so it'll be an approximation…)

The error you're seeing (`argument `$color` of `lightness($color)` must be a color`) is raised by libsass, not sass.js, so the issue is definitely with libsass.

> I'm starting to think that perhaps I'm not loading sass.js correctly in my project?

If you were not, you'd probably get no output at all.

> After preloading bourbon.io and my sass source files,

I don't think bourbon has anything to do with this, as [`lightness()`](http://sass-lang.com/documentation/Sass/Script/Functions.html#lightness-instance_method) is a built-in function.

**Comment by emyarod** [comment]
Ah, yeah I just included the bit about bourbon as a bit of context. I just tested using sass.js 0.9.4 and 0.9.5: No errors on 0.9.4, but I get the same error when using 0.9.5. Should I report this issue to the libsass devs?

**Comment by emyarod** [comment]
Ah, yeah I just included the bit about bourbon as a bit of context. I just tested using sass.js 0.9.4 and 0.9.5: No errors on 0.9.4, but I get the same error when using 0.9.5 so I'll downgrade to 0.9.4 for now. Should I report this issue to the libsass devs instead?

**Comment by rodneyrehm** [comment]
> Should I report this issue to the libsass devs instead?

yes, please. It seems that [libsass 3.3.3](https://github.com/sass/libsass/releases/3.3.3) introduced the problem. It would help them if you can provide a minimal test case. I.e. what exactly is the value you're trying to pass to `lightness()`. Good luck!
