### ISSUE TITLE
Is there any plan to create grunt plugin for sass.js?

### ISSUE THREAD

**Issue by amiramw** [medialize/sass.js#61]

**Comment by rodneyrehm** [comment]
Nope. Maybe [simple-sass](https://www.npmjs.com/package/simple-sass) (CLI for sass.js) helps?

**Comment by amiramw** [comment]
I created an initial grunt plugin https://github.com/amiramw/grunt-contrib-sassjs. Hope it's ok. Not yet released to npm.
If you could review it would be great...

**Comment by rodneyrehm** [comment]
* I think it would be a very good idea to keep the API as close to [grunt-sass](https://github.com/sindresorhus/grunt-sass) as possible. (Just note that the [functions options](https://github.com/sass/node-sass#functions--v300---experimental) are currently not supported by Sass.js)
* You currently limit to `.scss`, but that's not necessarily correct, `.sass` and `.css` are fine, too. see [`_libsassPathVariations()`](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L61-L82)
* It looks like you [scan the entire project to import all `.scss` files](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L23-L39) instead of using an [Importer callback](https://github.com/medialize/sass.js/#importer-callback-function) to resolve files on demand.
* [you're using `Sass.compile()`](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L50) instead of [`sass.compileFile()`](https://github.com/medialize/sass.js/#using-the-sassjs-api)
* If it is at all possible to load and run Sass.js in a separate process, you'd greatly help everyone running tasks in parallel, as Sass.js runs synchronously and thereby blocks the loop…

**Comment by amiramw** [comment]
Thanks for the feedback.
I think I covered most of the comments. Still need to look into the separate process thing.
Any more comments are welcome.

**Comment by rodneyrehm** [comment]
> Thanks for the feedback.

Thanks for your efforts!

> Still need to look into the separate process thing.

I don't think that's the most important thing for now…

> Any more comments are welcome.

### Parsing and mutating paths

The [importer callback](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L24-L38) looks like it's trying to mimic a subset of [_libsassPathVariations()](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L61-L82). Maybe we should talk about how we can expose this function so you can use it like [_resolvePath()](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L84-L97)?

You want to use the [Path module](https://nodejs.org/api/path.html) instead of playing the string manipulation game:

* https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L7-L9 - `Path.basename(file)`
* https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L25-L27 - `Path.dirname()`, `Path.basename()`, `Path.join()`, …
* https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L52 - `Path.basename(file)[0]`

### Error Handling:

* sass.js and libsass errors ([`result.status !== 0`](https://github.com/medialize/sass.js/#compile-response-object)) are [not passed to grunt](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L71-L74).

### SourceMaps

* If you'd return the actual path [when calling done()](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L21-L23), the generated SourceMaps would point to real files.
* The [generated SourceMap](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L60-L68) is missing the `sourcesContent` property.

**Comment by amiramw** [comment]
Fixed most of the comments. For now I copied [_libsassPathVariations()](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L61-L82). Let me know if you export it.

**Comment by rodneyrehm** [comment]
> Fixed most of the comments. 

which ones didn't you fix and why?

> Let me know if you export it.

As of [0.9.12](https://github.com/medialize/sass.js/releases/tag/0.9.12) you no longer need your copy of `_libsassPathVariations()`, but can now obtain that list from Sass.js directly, see [Resolving file names](https://github.com/medialize/sass.js/#resolving-file-names).

---

I would rewrite [your source map handling](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js#L79-L89) to

```js
var rootDirectory = "sass/" + PATH.dirname(src);
result.map.file = cssFile;
result.map.sources == result.map.sources.map(function (source) {
  return PATH.relative(rootDirectory, source).replace("\\", "/");
}),
grunt.file.write(cssFullPath + ".map", JSON.stringify(result.map));
```
Since you're using `Sass.compileFile()`, you don't need to filter `stdin` anymore. Since `results.map` already contains the map, there's no need to create a new object.

**Comment by amiramw** [comment]
> which ones didn't you fix and why?

At first I didn't populate the ``` sourcesContent ``` property as I understood it is optional in source map.

However I adopt your suggestion for ``` JSON.stringify(result.map) ``` and the ``` sourcesContent ``` is populated.
Also I now reuse ``` getPathVariations ``` from sass.js.

Thanks a lot for the help.

https://github.com/amiramw/grunt-contrib-sassjs/commit/a65f869df967a4e417c4260fd93239e4f0bc55ee

**Comment by rodneyrehm** [comment]
thanks for your efforts!
