### ISSUE TITLE
Not enough space failure when using importer with many files

### ISSUE THREAD

**Issue by amiramw** [medialize/sass.js#66]
I'm encountering issue on windows machine when importing a lot of big scss files using `Sass.importer`. In this case after several "Reading" file messages I'm getting:

```
Internal Error: Not enough space
```

My importer callback reads the content of the file from the file system and return it (see [here](https://github.com/amiramw/grunt-contrib-sassjs/blob/master/tasks/sass.js))

If instead of relying on the importer I call for each file `Sass.writeFile` and `Sass.compileFile` it works fine.
Another interesting thing is that it doesn't reproduce on linux.

Thanks

**Comment by rodneyrehm** [comment]
Interesting.

* Is there a stack trace for that "Not enough space" error?
* Are you able to [build sass.js](https://github.com/medialize/sass.js#building-sassjs) yourself, in order to figure out if this problem still exists with the latest release (1.36.11).
* Can you provide demo content SCSS files that allow reproducing the issue?

**Comment by rodneyrehm** [comment]
closing since there's been no response in nearly 2 months.
