### ISSUE TITLE
Failed to construct 'Worker': Script at .....

### ISSUE THREAD

**Issue by mikethedj4** [medialize/sass.js#84]
https://codepen.io/mikethedj4/pen/EXBjwd?editors=1010

Originally I was getting...

> Uncaught ReferenceError: sass is not defined

Which was probably due to the fact that `https://sass.js.org/js/sass.js/sass.js` is not served with a valid certificate. So instead I got it from [cdnjs.com][1]. Now I'm no longer getting `sass is not defined` but rather...

> Uncaught DOMException: Failed to construct 'Worker': Script at 'https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.5/sass.worker.min.js' cannot be accessed from origin

I'm not sure what I'm doing wrong here. I'm following the [instructions on sass.js.org](https://github.com/medialize/sass.js/blob/master/docs/getting-started.md) and I cannot get past these errors.

Here's my Javascript. Can someone explain what I'm doing wrong and how I can get this to run?

```
var code = document.getElementById('code'),
    sass = new Sass('https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.5/sass.worker.min.js'),
    scss = "$someVar: 123px; .some-selector { width: $someVar; }";

sass.compile(scss, function(result) {
  code.value = result;
  console.log(result);
});
```

**Comment by rodneyrehm** [comment]
This is following #83. Please note that you *can* reply to closed issues. Since you're not reporting a problem with the library itself there's no point in keeping your issue *open*, but that doesn't mean you can't continue the conversation (or re-open the issue if necessary)…

---

> > Uncaught DOMException: Failed to construct 'Worker': Script at 'https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.5/sass.worker.min.js' cannot be accessed from origin
>
> I'm not sure what I'm doing wrong here. I'm following the [instructions on sass.js.org](https://github.com/medialize/sass.js/blob/master/docs/getting-started.md) and I cannot get past these errors.

Although not mentioned specifically on the getting started page, general WebWorker rules apply. In this case it's the same-origin policy problem mentioned in [Using Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers):

> **Note:** The URI passed as a parameter to the Worker constructor must obey the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).
> 
> There is currently disagreement among browsers vendors on what URIs are of the same-origin; Gecko 10.0 (Firefox 10.0 / Thunderbird 10.0 / SeaMonkey 2.7) and later do allow data URIs and Internet Explorer 10 does not allow Blob URIs as a valid script for workers.

If you *have* to load the script from a foreign origin (as will be the case with any CDN), I'd suggest you have a look at [how to create a worker from string](https://stackoverflow.com/a/10372280/515124) and [fetch](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) (or [XHR](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest)).

**Comment by mikethedj4** [comment]
I even ran it on my own server and it still gives me that error so I don't think the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) would be prevalent in that case cause I'm trying to use it for offline usage.

**Comment by rodneyrehm** [comment]
> I even ran it on my own server

is that publicly accessible? can I have a look?

Does cloning this repository and openening `sass.worker.html` in your browser work for you? (try [local-web-server](https://www.npmjs.com/package/local-web-server) if you don't have that setup locally)

**Comment by mikethedj4** [comment]
lol nvm I figured out the problem
