### ISSUE TITLE
Using Sass.js in the browser with Webpack

### ISSUE THREAD

**Issue by aapoalas** [medialize/sass.js#95]
Hello sirs!

You have a wonderful, informative and simple documentation on how to use Sass.js in the browser with a module loader. But I am trying to figure out usage when using Webpack as the module loader. Now this sets up the challenge that the worker files come out as `[hash].worker.js` as default, so letting Sass.js know the Worker path as a string is a challenge. (Of course this could actually be circumvented by simply changing the worker files to `[name].worker.js` but lets not get caught in the details...)

Can you think of a way to allow Webpack to handle the worker loading without explicitly defining the worker file names?

EDIT: The answer to my question is, essentially: "No."

The longer answer is to use CopyWebpackPlugin to handle the copying of the worker file (and the wasm file in 0.11.0-beta.1 branch) to the output folder and explicitly defining the worker file names to those copied files.

**Comment by rodneyrehm** [comment]
Why do you need webpack to handle the worker file? It's already minified any further processing *could* break things. With [0.11.0-beta.1](https://github.com/medialize/sass.js/releases/tag/0.11.0-beta.1) this would get even worse, because the worker file (JS) has to load a second file (WebAssembly). I'd suggest to try copying `dist/*` to your build target (e.g. by using [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin)) instead.

**Comment by aapoalas** [comment]
That is, in the end, what I went with.

The reason for why I wanted to avoid it, though, was that I dislike all copy and symlink plugins and think them ugly :) ie. Personal preference. I like automagic, and dislike manual.

**Comment by rodneyrehm** [comment]
I agree, but I don't see a good way to avoid copying things around :(
